# -*- coding: utf-8 -*-
"""tutorial_plotly

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uuW-D1R7VTjnLGuR3-VKovjr4MF6Oldv

Instruções

Implemente uma função em Python chamada processar_texto_simulado. Esta função deverá simular as principais etapas de pré-processamento de um texto, são elas:

- Tokenização;
- Remoção de Stopwords e Lematização;
- Contagem de Frequência.

A função deverá ter um return adequado, porém não executado, pois o Lab Tech não executa o código nem permite o uso de bibliotecas externas (como NLTK ou spaCy), seu objetivo é construir a estrutura lógica da função.

Adicione comentários no código para indicar onde cada etapa do processo ocorreria em uma aplicação real.


Entrega:

- Linguagem: Python;
- Estruturas esperadas: listas, dicionários, tuplas;
- Não utilize bibliotecas externas;
- Não inclua instruções de execução, simulação ou testes no código.
"""

def processar_texto_simulado(texto):
    # Etapa 1: Tokenização
    tokens = texto.split()  # Simulação da tokenização

    # Etapa 2: Remoção de Stopwords e Lematização
    stopwords = {'e', 'a', 'o', 'que', 'de', 'do', 'da', 'em', 'para', 'com'}  # Exemplo de stopwords
    tokens_filtrados = [token for token in tokens if token.lower() not in stopwords]  # Remoção de stopwords

    # Simulação de lematização
    lematizados = [token.lower() for token in tokens_filtrados]  # Simulação da lematização

    # Etapa 3: Contagem de Frequência
    frequencia = {}
    for token in lematizados:
        if token in frequencia:
            frequencia[token] += 1
        else:
            frequencia[token] = 1

    # Retorno da contagem de frequência
    return frequencia  # Retorno da estrutura de dados com a contagem de frequência

# Exemplo de uso da função
texto_exemplo = "A casa é bonita e a vista é linda"
resultado = processar_texto_simulado(texto_exemplo)
print(resultado)  # Exibe o resultado da contagem de frequência

